### ISSUE TITLE
Processing GetOwnedGamesRequest throws exception java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by elln2** [lpradel/steam-web-api-java#3] opened 2015-10-12 17:30 UTC
When using GetOwnedGames, processing the request throws java.lang.IllegalArgumentException due to Illegal character in query at index 125 in  https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?format=json&key=3F66197689D7D799CC7378980235F678&input_json={"steamid":"76561198039505218"}

The character at index 125 is the opening curly brace, {. The URL is a valid call to a service interface but the brace causes the exception. Changing the steam ID does not resolve the issue.

**Comment by elln2** [comment] 2015-10-12 20:41
Same for GetRecentlyPlayedGames

**Comment by lpradel** [comment] 2015-10-17 18:19
This bug is caused by the JSON object not being property URL-encoded. I will fix it in 1.2. Thank your for reporting it!

**Comment by lpradel** [comment] 2015-10-17 19:48
Fix #3 - Request URLs are now properly URL-encoded (fixed by 60e1a6f83caf60d37e67b3004e20ab1fb3b613ad)

JSON objects in the request string are now properly URL-encoded by the
URI builder

**Closed by lpradel** 2015-10-17 19:48 UTC
Labels: bug
